/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommonHeader: typeof import('./../src/components/common/CommonHeader.vue')['default']
    CommonLogo: typeof import('./../src/components/common/CommonLogo.vue')['default']
    NavItem: typeof import('./../src/components/nav/NavItem.vue')['default']
    NavMain: typeof import('./../src/components/nav/NavMain.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
